### ISSUE TITLE
DayNightCycleService days not starting at 1

### ISSUE THREAD

**Issue by cholnhial** [UQdeco2800/2022-studio-1#169]
## Description
in `DayNightCycleService` when subscribing to the event `EVENT_DAY_PASSED` the first day is passed in as 0 instead of 1.

## How To Reproduce
Steps to reproduce the behaviour:
1.  Create a method that receives and Integer as a parameter for day
2. subscribe to the event through `ServiceLocator.getDayNightCycleService().getEvents().addListener(DayNightCycleService.EVENT_DAY_PASSED, this::yourmethod)`
3. Put a breakpoint somewhere in the middle of the body of your method and inpsect the passed in value
4. It should be 0 for the first call. Alternatively use logging

## Expected Behaviour
The expected behaviour is for the service to begin days from 1 and forward 

## Temporary Fix
A temporary workaround would be to call `getCurrentDayNumber()` immediately after receiving the event.

**Comment by cholnhial** [comment]
This bug was reported by @setoaprasetyo

**Comment by setoaprasetyo** [comment]
The event subscription is working as intended

**Comment by cholnhial** [comment]
> The event subscription is working as intended

It turns out thre was still a bug present. When max day is 1 the first day is sent to be 0 when it should be 1. Also the correct sequence of days was not followed. A fix has been applied to address these.
