### ISSUE TITLE
Background design

### ISSUE THREAD

**Issue by taylaward** [UQdeco2800/2022-studio-1#36]
# **Description**
**Task:** [Background design](#3).
**Feature:** [Background Design and Water Metrics](#30 )
Start on background design (Aug. 26)

Design the background that the map will be placed on. I.e the sky, day/night, or random background art

# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create Background
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
To be implementing
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)

**Comment by taylaward** [comment]
Removed from Sprint 1

**Comment by applebyter** [comment]
You need to remove items from the template that are not relevant.
