### ISSUE TITLE
Landscape Objects 

### ISSUE THREAD

**Issue by MichelleAsWell** [UQdeco2800/2022-studio-1#6]
# **Description**
Our team plans to implement `Landscape Objects` which will be generated on the map when it is created. These objects will interact with entities (both player character and enemies) in various ways, such as preventing collision and slowing movement or adding extra powerup features. They will also be removable from the map by the player, and may provide resources when removed (e.g. a removed boulder will provide the player with building materials, an Atlantis sentinel will kill 20 enemies). Adding such features will improve immersion in the game, impact the gameplay, increase the interest level of the map, and provide a secondary avenue for player progression (the clearing of land to build further).

## SubFeature/component 
- `Obstacles` and `Artefacts` will be generated on map creation. Seed based system possible
- `Obstacles` will interact with entities in meaningful ways
- `Artefacts` will provide useful powerups when collected
- Different `obstacles` will provide different interactions (cobwebs slow, boulders are impassable, ruins provide bonus currency /may spawn monsters)
- `Obstacles` will be removable by the player, and will provide `resources` when removed

## **Examples**
- **Generation**: `Landscape objects` will be generated when the game starts, using a seed-based system
- **Obstacles**: `obstacles` will impede movement, and when removed will grant resources
- **Artefacts**: `Artefacts` will be collectable by the player and will provide useful powerups when collected, such as increased attack speed, increased resource gathering, etc.

# **Dependencies**
Object placement will depend on map grids and landscape generation
Resources granted by removed objects will depend on an implemented resource pool (either falls under UI or main character)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] **Goal 1** (Aug. 20)
- List of required objects completed, including relevant features (e.g. size)
- Object interaction designs completed
- Generic `Landscape Object` class created for use in sub-tasks
- Base sub-classes for `artefacts` and `obstacles` created
- [x] Goal 2 (Aug. 23)
- Collision physics implemented (maybe give each type an interface)
- [x] Goal 3 (Aug. 26)
- Object assets completed
- Object generation completed
- Specific artefacts implemented (powerups, timers?)
- Specific objects implemented (collision, resource grant)
- [x] Goal 4 (Aug. 28)
- Finalised, integrated with landscape grid (team 3)
- Objects and assets combined
- Testing completed

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Day/night cycle (timer & darkness - monster spawns & music will depend on other teams)
- [ ] Different biomes
- [ ] Dynamic water level

# **Documentation**
- [Main description of feature](../wiki/Landscape-Objects)
- [User documentation](../wiki/Game-Guide#section1)

# **Members**
- Michelle (@MichelleAsWell) (Michelle Sands)
- Aleks (@a-siroki) (Aleks Siroki)
- Seto (@setoaprasetyo) (Seto Adhi Prasetyo)
- Logan (@Logan-De-Groot)(Logan De Groot)
- Annabel (@Annabel-Kennedy)(Annabel Kennedy)

**Comment by luke4641942** [comment]
Just a quick revision about what we (team 5) discussed with you guys in the studio on Wednesday. We spoke about how you guys are planning to put collidable landforms in/on some of your blocks where buildings cant be placed. If it can be implemented with main character, we spoke about the main character being able to mine (turn the block to grass instead and collect the resources) what's on the block so that buildings could then be placed there and collect resources at the same time.

**Comment by Logan-De-Groot** [comment]
@luke4641942 

Currently Team 4 is thinking that when a enviromental object/block/tree etc is destroyed by a player you can access the amount of resources via the getResourceMethod before fully removing the Entity object. See the team-4 branch specifically file: source/core/src/main/com/deco2800/game/components/Enviromental/EnvironmentalComponent.java
for initial design. Happy to discuss further changes inline with what you need and what Team 4 requires

**Comment by MichelleAsWell** [comment]
Rethought the feature ticket with dev members of team 4 today, changed expectations  to be more realistic for an initial sprint (removed expectations for things like artefacts that give attack speed, etc. which require excessive integration for other teams, and anything that requires a timer, which will be tough to figure out in time)
